package com.coldridge.valley.job.dao.meishi.write.mbg;

import com.coldridge.valley.job.model.po.Huoguo;
import com.coldridge.valley.job.model.po.HuoguoExample;
import org.apache.ibatis.annotations.Param;

public interface MBGHuoguoWriteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int deleteByExample(HuoguoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int insert(Huoguo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int insertSelective(Huoguo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Huoguo record, @Param("example") HuoguoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Huoguo record, @Param("example") HuoguoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Huoguo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Huoguo record);
}