package com.coldridge.valley.job.model.po;

import java.util.ArrayList;
import java.util.List;

public class HuoguoExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public HuoguoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopAddrIsNull() {
            addCriterion("shop_addr is null");
            return (Criteria) this;
        }

        public Criteria andShopAddrIsNotNull() {
            addCriterion("shop_addr is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddrEqualTo(String value) {
            addCriterion("shop_addr =", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrNotEqualTo(String value) {
            addCriterion("shop_addr <>", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrGreaterThan(String value) {
            addCriterion("shop_addr >", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrGreaterThanOrEqualTo(String value) {
            addCriterion("shop_addr >=", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrLessThan(String value) {
            addCriterion("shop_addr <", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrLessThanOrEqualTo(String value) {
            addCriterion("shop_addr <=", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrLike(String value) {
            addCriterion("shop_addr like", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrNotLike(String value) {
            addCriterion("shop_addr not like", value, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrIn(List<String> values) {
            addCriterion("shop_addr in", values, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrNotIn(List<String> values) {
            addCriterion("shop_addr not in", values, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrBetween(String value1, String value2) {
            addCriterion("shop_addr between", value1, value2, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andShopAddrNotBetween(String value1, String value2) {
            addCriterion("shop_addr not between", value1, value2, "shopAddr");
            return (Criteria) this;
        }

        public Criteria andStartMoneyIsNull() {
            addCriterion("start_money is null");
            return (Criteria) this;
        }

        public Criteria andStartMoneyIsNotNull() {
            addCriterion("start_money is not null");
            return (Criteria) this;
        }

        public Criteria andStartMoneyEqualTo(Long value) {
            addCriterion("start_money =", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyNotEqualTo(Long value) {
            addCriterion("start_money <>", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyGreaterThan(Long value) {
            addCriterion("start_money >", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("start_money >=", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyLessThan(Long value) {
            addCriterion("start_money <", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyLessThanOrEqualTo(Long value) {
            addCriterion("start_money <=", value, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyIn(List<Long> values) {
            addCriterion("start_money in", values, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyNotIn(List<Long> values) {
            addCriterion("start_money not in", values, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyBetween(Long value1, Long value2) {
            addCriterion("start_money between", value1, value2, "startMoney");
            return (Criteria) this;
        }

        public Criteria andStartMoneyNotBetween(Long value1, Long value2) {
            addCriterion("start_money not between", value1, value2, "startMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyIsNull() {
            addCriterion("avg_money is null");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyIsNotNull() {
            addCriterion("avg_money is not null");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyEqualTo(Long value) {
            addCriterion("avg_money =", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyNotEqualTo(Long value) {
            addCriterion("avg_money <>", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyGreaterThan(Long value) {
            addCriterion("avg_money >", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("avg_money >=", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyLessThan(Long value) {
            addCriterion("avg_money <", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyLessThanOrEqualTo(Long value) {
            addCriterion("avg_money <=", value, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyIn(List<Long> values) {
            addCriterion("avg_money in", values, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyNotIn(List<Long> values) {
            addCriterion("avg_money not in", values, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyBetween(Long value1, Long value2) {
            addCriterion("avg_money between", value1, value2, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andAvgMoneyNotBetween(Long value1, Long value2) {
            addCriterion("avg_money not between", value1, value2, "avgMoney");
            return (Criteria) this;
        }

        public Criteria andShopLinkIsNull() {
            addCriterion("shop_link is null");
            return (Criteria) this;
        }

        public Criteria andShopLinkIsNotNull() {
            addCriterion("shop_link is not null");
            return (Criteria) this;
        }

        public Criteria andShopLinkEqualTo(String value) {
            addCriterion("shop_link =", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkNotEqualTo(String value) {
            addCriterion("shop_link <>", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkGreaterThan(String value) {
            addCriterion("shop_link >", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkGreaterThanOrEqualTo(String value) {
            addCriterion("shop_link >=", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkLessThan(String value) {
            addCriterion("shop_link <", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkLessThanOrEqualTo(String value) {
            addCriterion("shop_link <=", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkLike(String value) {
            addCriterion("shop_link like", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkNotLike(String value) {
            addCriterion("shop_link not like", value, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkIn(List<String> values) {
            addCriterion("shop_link in", values, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkNotIn(List<String> values) {
            addCriterion("shop_link not in", values, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkBetween(String value1, String value2) {
            addCriterion("shop_link between", value1, value2, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopLinkNotBetween(String value1, String value2) {
            addCriterion("shop_link not between", value1, value2, "shopLink");
            return (Criteria) this;
        }

        public Criteria andShopStarsIsNull() {
            addCriterion("shop_stars is null");
            return (Criteria) this;
        }

        public Criteria andShopStarsIsNotNull() {
            addCriterion("shop_stars is not null");
            return (Criteria) this;
        }

        public Criteria andShopStarsEqualTo(Integer value) {
            addCriterion("shop_stars =", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsNotEqualTo(Integer value) {
            addCriterion("shop_stars <>", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsGreaterThan(Integer value) {
            addCriterion("shop_stars >", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_stars >=", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsLessThan(Integer value) {
            addCriterion("shop_stars <", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsLessThanOrEqualTo(Integer value) {
            addCriterion("shop_stars <=", value, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsIn(List<Integer> values) {
            addCriterion("shop_stars in", values, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsNotIn(List<Integer> values) {
            addCriterion("shop_stars not in", values, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsBetween(Integer value1, Integer value2) {
            addCriterion("shop_stars between", value1, value2, "shopStars");
            return (Criteria) this;
        }

        public Criteria andShopStarsNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_stars not between", value1, value2, "shopStars");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huoguo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}