package com.coldridge.valley.job.dao.meishi.read.mbg;

import com.coldridge.valley.job.model.po.Huoguo;
import com.coldridge.valley.job.model.po.HuoguoExample;
import java.util.List;

public interface MBGHuoguoReadDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    int countByExample(HuoguoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    List<Huoguo> selectByExample(HuoguoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    Huoguo selectByPrimaryKey(Long id);
}