package com.coldridge.valley.job.model.po.mbg;

public class Huoguo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.id
     * 主键
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.type
     * 类型 0:火锅
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.shop_name
     * 店铺名
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.shop_addr
     * 店铺地址
     *
     * @mbggenerated
     */
    private String shopAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.start_money
     * 多少钱起  单位 分
     *
     * @mbggenerated
     */
    private Long startMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.avg_money
     * 平均消费 单位 分
     *
     * @mbggenerated
     */
    private Long avgMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.shop_link
     * 店铺连接
     *
     * @mbggenerated
     */
    private String shopLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huoguo.shop_stars
     * 店铺评分 满分100
     *
     * @mbggenerated
     */
    private Integer shopStars;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.id
     *
     * @return the value of huoguo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.id
     *
     * @param id the value for huoguo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.type
     *
     * @return the value of huoguo.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.type
     *
     * @param type the value for huoguo.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.shop_name
     *
     * @return the value of huoguo.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.shop_name
     *
     * @param shopName the value for huoguo.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.shop_addr
     *
     * @return the value of huoguo.shop_addr
     *
     * @mbggenerated
     */
    public String getShopAddr() {
        return shopAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.shop_addr
     *
     * @param shopAddr the value for huoguo.shop_addr
     *
     * @mbggenerated
     */
    public void setShopAddr(String shopAddr) {
        this.shopAddr = shopAddr == null ? null : shopAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.start_money
     *
     * @return the value of huoguo.start_money
     *
     * @mbggenerated
     */
    public Long getStartMoney() {
        return startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.start_money
     *
     * @param startMoney the value for huoguo.start_money
     *
     * @mbggenerated
     */
    public void setStartMoney(Long startMoney) {
        this.startMoney = startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.avg_money
     *
     * @return the value of huoguo.avg_money
     *
     * @mbggenerated
     */
    public Long getAvgMoney() {
        return avgMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.avg_money
     *
     * @param avgMoney the value for huoguo.avg_money
     *
     * @mbggenerated
     */
    public void setAvgMoney(Long avgMoney) {
        this.avgMoney = avgMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.shop_link
     *
     * @return the value of huoguo.shop_link
     *
     * @mbggenerated
     */
    public String getShopLink() {
        return shopLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.shop_link
     *
     * @param shopLink the value for huoguo.shop_link
     *
     * @mbggenerated
     */
    public void setShopLink(String shopLink) {
        this.shopLink = shopLink == null ? null : shopLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huoguo.shop_stars
     *
     * @return the value of huoguo.shop_stars
     *
     * @mbggenerated
     */
    public Integer getShopStars() {
        return shopStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huoguo.shop_stars
     *
     * @param shopStars the value for huoguo.shop_stars
     *
     * @mbggenerated
     */
    public void setShopStars(Integer shopStars) {
        this.shopStars = shopStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huoguo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", shopName=").append(shopName);
        sb.append(", shopAddr=").append(shopAddr);
        sb.append(", startMoney=").append(startMoney);
        sb.append(", avgMoney=").append(avgMoney);
        sb.append(", shopLink=").append(shopLink);
        sb.append(", shopStars=").append(shopStars);
        sb.append("]");
        return sb.toString();
    }
}